services:
  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: 'Asia/Kolkata'
      SERVER_ADMIN: 'admin@homelabindia.org'
      HTTP_SERVER_NAME: 'homelabindia.org'
      HTTPS_SERVER_NAME: 'homelabindia.org'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - linkstack:/htdocs
    ports:
      - '8190:443'
    restart: unless-stopped
volumes:
  linkstack: